### ISSUE TITLE
Subproject points to local path

### ISSUE THREAD

**Issue by dalb8** [acl33/AndroidDasher#2]
The default.properties file, references a project which points to a directory in the authors computer. Could this explain why I can't build it?.

**Comment by dalb8** [comment]
The error is this: vac] Compiling 88 source files to /home/gerry/dalb8s-fdroiddata/build/dasher.android/bin/classes
    [javac] /home/gerry/dalb8s-fdroiddata/build/dasher.android/src/dasher/CAlphIO.java:312: warning: unmappable character for encoding UTF-8
    [javac]             String name=null; String ctxEscape="�";

**Comment by acl33** [comment]
Really? Ooops, let me see...

Ah, it's a relative path, that'll be how I missed it. It's supposed to
point to the Tecla SDK for accessing the external switch, but that
directory doesn't actually exist on my own computer, yet the project still
builds fine - possibly using Eclipse project inclusion, but I'm not sure if
you even need that...

...as the error you've got, is certainly nothing to do with missing paths,
but something to do with Unicode encodings. It's possible the file's
somehow got corrupted by pushing it through github, or that your
computer/Eclipse is set up differently. Have a look in your training file
and see if there's a large number of some escape character, and if so try
that, else you can change it to any character you don't actually want to
write...

However, I see now that that message says it's only a warning, rather than
an error, so it shouldn't be stopping you from building anything. Can you
look further and see if there are any more actual errors?

HTH, Alan

**Comment by dalb8** [comment]
You're right. The actual errors are all the same: [javac] /home/gerry/dalb8s-fdroiddata/build/dasher.android/src/dasher/CAlphabetManager.java:191: ')' expected
    [javac]             CAlphabetManager<?>.CAlphNode nn = (CAlphabetManager<?>.CAlphNode)n;

**Comment by dalb8** [comment]
Referencing the Tecla SDK, I get:
`[javac] /home/gerry/fdroiddata/build/dasher.android/InputAccessLib/library/src/ca/idi/tecla/lib/menu/MenuDialog.java:14: error: cannot find symbol
    [javac] import android.content.DialogInterface.OnShowListener;
    [javac]                                       ^
    [javac]   symbol:   class OnShowListener
    [javac]   location: interface DialogInterface
    [javac] /home/gerry/fdroiddata/build/dasher.android/InputAccessLib/library/src/ca/idi/tecla/lib/menu/MenuDialog.java:100: error: cannot find symbol
    [javac]         dialog.setOnShowListener(new OnShowListener() {
    [javac]                                      ^
    [javac]   symbol:   class OnShowListener
    [javac]   location: class MenuDialog
    [javac] 2 errors
`
But I'm not sure which commit to use for these libraries. It's asking for java.awt too.

**Comment by acl33** [comment]
Ah, yes, sorry. So it looks like it's complaining about the cast to
(CAlphabetManager<?>.CAlphNode)...

Well, it looks like legal Java to me; CAlphNode is a non-static inner
class. And it builds fine on Eclipse. How are you trying to build it? Is
this yet another case of the "official" Java compiler being a poor
implementation of the official Java language definition? (This has happened
many times before, usually Eclipse has turned out to be right and the JDK
wrong. And it looks OK to me. What javac are you using?)

--Alan

**Comment by dalb8** [comment]
I'm using an up to date openjdk 1.6. I messed around and added the tekla stuff and now I'm coming up against java.awt -- from what I read that doesn't belong in Android.

**Comment by acl33** [comment]
Correct. You should be able to build the applet as a separate project in
eclipse, or remove it altogether if you only care about the Android...

**Comment by dalb8** [comment]
Thanks for the tip, I got it working. In summary: checkout TeclaAccess @ ee65057ff8; rm -rf src/dasher/applet; sed -i 's@(reference.1=).*@\1$$TeclaAccess$$@' project.properties && \
printf 'android.library=true' >> $$TeclaAccess$$/project.properties && \
sed -i 's/debuggable="true"/debuggable="false"/g' AndroidManifest.xml. I'll publish put my recipe into the F-Droid repository and the apk will shortly be available to download from f-droid.org.
